esphome:
  name: display-consumi-casa
  friendly_name: "Display Consumi Casa"

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: "Display-Consumi Fallback"
    password: "12345678"

captive_portal:

logger:
  level: INFO

api:
  encryption:
    key: !secret api_encryption_key

ota:
  - platform: esphome
    password: !secret ota_password

i2c:
  sda: GPIO5
  scl: GPIO6
  scan: true
  id: bus_a

font:
  - file: "gfonts://Roboto"
    id: font_small
    size: 14

sensor:
  - platform: homeassistant
    id: consumo_casa
    entity_id: sensor.shellyem_c7f7a1_channel_1_power
    internal: true

  - platform: wifi_signal
    name: "Display WiFi Signal"
    update_interval: 60s

display:
  - platform: ssd1306_i2c
    model: "SSD1306 72x40"
    address: 0x3C
    i2c_id: bus_a
    id: oled_display
    update_interval: 2s
    lambda: |-
      if (id(consumo_casa).has_state()) {
        it.printf(36, 20, id(font_small), TextAlign::CENTER,
                   "%.0f W", id(consumo_casa).state);
      } else {
        it.printf(36, 20, id(font_small), TextAlign::CENTER, "-- W");
      }
